name: Build Draft Release

on:
  workflow_dispatch:
    inputs:
      package-semver:
        description: Semantic version to release
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create release files
        run: bash make.sh
        id: create-release-files
      - name: Create release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.package-semver }}
          release_name: ${{ github.event.inputs.package-semver }}
          draft: true
          prerelease: false
          body: 'Sublime-Text-Version-Range: >=4070'
      - name: Upload Zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: out/release.zip
          asset_name: LSP-jdtls.zip
          asset_content_type: application/zip
